-- Удаление старых таблиц если уже имеются
drop table if exists user_title, permissions, users, titles, title_types;

-- Создание таблицы пользователей
create table users (
  id integer primary key generated by default as identity,
  email varchar(64) not null unique,
  username varchar(64) not null unique,
  encoded_password varchar(128) not null,
  is_active boolean,
  is_locked boolean
);
-- Настройка индексирования email
create index email_idx on users (email);

-- Создание таблицы разрешений пользователя
create table user_permissions (
    id integer primary key references users (id) on delete cascade,
    PERM_EDIT_TITLES boolean,
    PERM_EDIT_TYPES boolean,
    PERM_EDIT_USERS boolean
);

-- Создание таблицы типов тайтлов
create table title_types (
    code_name varchar(16) primary key,
    display_name varchar(32) unique
);

-- Создание таблицы тайтлов
create table titles (
    id integer primary key generated by default as identity,
    name varchar(128) not null unique,
    cover_url varchar(128),
    type varchar(16) references title_types (code_name) on delete cascade
);
create index title_idx on titles (lower(name));

-- Создание таблицы состояния употребления контента
create table user_title (
    user_id integer references users (id) on delete cascade,
    title_id integer references titles (id) on delete cascade,
    state varchar(16),
    unique (user_id, title_id)
);